package com.ingramcontent;

import com.ingramcontent.model.Request;
import com.ingramcontent.consumer.RestWebServiceConsumer;

rule "Update Product Inventory"
    ruleflow-group 'UpdateProductInventory'
	when 
		request: Request(method=="GET");
	then
	    String url = "https://ingramcontent.com/api/v1/productCatalog/updateProductInventory";
		String response = RestWebServiceConsumer.get(url);
		request.setResponse(response);
	end	


rule "Refresh Product Feed"
    ruleflow-group 'RefreshProductFeed'
	when 
		request: Request(method=="GET");
	then
	    String url = "https://ingramcontent.com/api/v1/product/refreshProductFeed";
		String response = RestWebServiceConsumer.get(url);
		request.setResponse(response);
	end	



rule "Refresh Inventory Feed"
    ruleflow-group 'RefreshInventoryFeed'
	when 
		request: Request(method=="GET");
	then
	    String url = "https://ingramcontent.com/api/v1/product/refreshInventoryFeed";
		String response = RestWebServiceConsumer.get(url);
		request.setResponse(response);
	end	


rule "Refresh Review Feed"
    ruleflow-group 'RefreshReviewFeed'
	when 
		request: Request(method=="GET");
	then
	    String url = "https://ingramcontent.com/api/v1/product/refreshReviewFeed";
		String response = RestWebServiceConsumer.get(url);
		request.setResponse(response);
	end		
	
rule "Fetch Feed Status"
    ruleflow-group 'FetchFeedStatus'
	when 
		request: Request(method=="GET");
	then
	    String url = "https://gorest.co.in/public/v2/todos";
		String response = RestWebServiceConsumer.get(url);
		request.setResponse(response);
	end	