package com.ingramcontent;

import com.ingramcontent.model.Request;
import com.ingramcontent.consumer.RestWebServiceConsumer;

rule "Refresh Product Feed"
    ruleflow-group 'RefreshProductFeed'
	when 
		request: Request(method=="GET");
	then
	    String url = "https://gorest.co.in/public/v2/todos";
		String response = RestWebServiceConsumer.get(url);
		request.setResponse(response);
	end	



rule "Get Product Feed Status"
    ruleflow-group 'GetProductFeedStatus'
	when 
		request: Request(method=="GET");
	then
	    String url = "https://gorest.co.in/public/v2/todos";
		String response = RestWebServiceConsumer.get(url);
		request.setResponse(response);
	end	


rule "Refresh Inventory Feed"
    ruleflow-group 'RefreshInventoryFeed'
	when 
		request: Request(method=="GET");
	then
	    String url = "https://gorest.co.in/public/v2/todos";
		String response = RestWebServiceConsumer.get(url);
		request.setResponse(response);
	end		