package com.ingramcontent.consumer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RestWebServiceConsumer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RestWebServiceConsumer() {
    }




}